import { api } from '../lib/api';

export const adminService = {
  login: (data: { email: string; password: string }) => api.post('/admin/login', data).then((r) => r.data),
  getUsers: (params?: any) => api.get('/admin/users', { params }).then((r) => r.data),
  getUser: (id: string) => api.get(`/admin/users/${id}`).then((r) => r.data.user),
  freezeUser: (id: string, freeze: boolean) => api.put(`/admin/users/${id}/freeze`, { freeze }).then((r) => r.data),
  updateKyc: (id: string, status: string) => api.put(`/admin/users/${id}/kyc`, { status }).then((r) => r.data),
  fundGas: (id: string) => api.post(`/admin/users/${id}/fund-gas`).then((r) => r.data),
  getWallets: (params?: any) => api.get('/admin/wallets', { params }).then((r) => r.data),
  freezeWallet: (address: string, freeze: boolean) => api.put(`/admin/wallets/${address}/freeze`, { freeze }).then((r) => r.data),
  getTransactions: (params?: any) => api.get('/admin/transactions', { params }).then((r) => r.data),
  getAnalyticsOverview: () => api.get('/admin/analytics/overview').then((r) => r.data),
  getAnalyticsCharts: (range?: string) => api.get('/admin/analytics/charts', { params: { range } }).then((r) => r.data),
  getTokenConfig: () => api.get('/admin/token/config').then((r) => r.data),
  updateFee: (fee: string) => api.put('/admin/token/fee', { fee }).then((r) => r.data),
  updateFeeAddress: (address: string) => api.put('/admin/token/fee-address', { address }).then((r) => r.data),
  togglePause: (pause: boolean) => pause ? api.post('/admin/token/pause') : api.delete('/admin/token/pause').then((r) => r.data),
  addFeeExempt: (address: string) => api.post('/admin/token/fee-exempt', { address }).then((r) => r.data),
  removeFeeExempt: (address: string) => api.delete(`/admin/token/fee-exempt/${address}`).then((r) => r.data),
  getTickets: (params?: any) => api.get('/admin/support/tickets', { params }).then((r) => r.data),
  replyTicket: (id: string, body: string) => api.post(`/admin/support/tickets/${id}/reply`, { body }).then((r) => r.data),
  closeTicket: (id: string) => api.post(`/admin/support/tickets/${id}/close`).then((r) => r.data),
  assignTicket: (id: string, adminId: string) => api.post(`/admin/support/tickets/${id}/assign`, { adminId }).then((r) => r.data),
  getAdmins: () => api.get('/admin/admins').then((r) => r.data),
  createAdmin: (data: any) => api.post('/admin/admins', data).then((r) => r.data),
  suspendAdmin: (id: string, suspend: boolean) => api.put(`/admin/admins/${id}/suspend`, { suspend }).then((r) => r.data),
  broadcastNotification: (data: { title: string; body: string; userId?: string }) => api.post('/admin/notifications/broadcast', data).then((r) => r.data),
  mintTokens: (data: { address: string; mfsAmount: string; ethAmount: string }) => api.post('/admin/token/mint', data).then((r) => r.data),
};
